name: 'mobile.dev Upload Action'
description: 'Upload app to mobile.dev for analysis'
inputs:
  api-url:
    description: 'Alternative mobile.dev API url'
    required: false
  api-key:
    description: 'mobile.dev API key'
    required: true
  name:
    description: 'Name of the version of the uploaded app'
    required: true
  app-file:
    description: 'The app file to upload to mobile.dev'
    required: true
  mapping-file:
    description: 'The Proguard mapping file to upload to mobile.dev'
    required: false
  workspace:
    description: 'Path to a folder that contains Maestro flows (.mobiledev by default)'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
